# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180531_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='static/img/default.jpg', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
