# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180531_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
            ],
            options={
                'db_table': '邮箱验证码',
            },
        ),
    ]
