# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_validcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidCode',
            new_name='EmailValidCode',
        ),
    ]
