# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180531_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
            ],
            options={
                'db_table': '书信息',
                'verbose_name': '书信息',
                'verbose_name_plural': '书信息',
            },
        ),
    ]
